import Wrapper from "@/layouts/wrapper";
import HomeOne from "@/components/homes/home";

export const metadata = {
  title: "Sachin Jadhav - Portfolio",
  description: "Generated by create next app",
};

const HomePage = () => {
  return (
    <Wrapper>
      <HomeOne />
    </Wrapper>
  );
};

export default HomePage;
